<?php 

/**
* Protects against comment form spam.
* @author benjamin birkenhake <benjamin@birkenhake.org>
*
*/

function sodom_form_alter(&$form, &$form_state, $form_id){
	//dprint_r($form_state);
	global $user;
	if($form_id == "comment_form" and $user->uid==0){
		$form['sodom'] = array(
			"#type" => "checkbox",
			"#title" => "Bin weder Hund noch Spambot.",
			);
	}
}

function sodom_comment(&$a1, $op){
	global $user;
	if($op== "validate" and $a1['sodom'] == 0 and $user->uid == 0 ){	
		watchdog("sodom", t("Dog or Spambot Attack")."! <br/> ".t("Name").":".$a1["name"]." <br/> ".t("Comment").": ".$a1["comment"], array(), WATCHDOG_INFO);
		form_set_error("sodom", "Dein Kommentar wurde NICHT gespeichert, weil Du noch einen Haken setzen musst, oder bist Du Hund oder Spambot?!");
	}
}